### ISSUE TITLE
Youtube Gallery Not working Now

### ISSUE THREAD

**Issue by APKone** [joomlaboat/YoutubeGallery#14] opened 2022-01-03 04:08 UTC
My Youtube Gallery Not working. Use to be part of the quota. Added my own Youtube API Key. Still not working.
http://www.route66moparclub.com/index.php/internet/social-media

**Comment by APKone** [comment] 2022-01-05 03:24
If I clear out the API Key I got from Youtube, and refresh the video list. all counters have "1". On the website, boxes are displayed with View of 0.

**Comment by joomlaboat** [comment] 2022-01-05 17:11
Hello APKone,

Please try to get your own Youtube Data API Key, this way your website will be independent of my Youtube quotas.

If you don't have Youtube Data API Key, follow this link to register your project and get the API Key
https://console.developers.google.com/

![image](https://user-images.githubusercontent.com/8064340/148259402-de2dd63e-ed2d-413f-978c-72d1ca30a16a.png)

**Comment by APKone** [comment] 2022-01-05 17:13
I got a key from youtube. Did not fix the issue.

Sent from Galaxy S8 far, far, away... 
 
  On Wed, Jan 5, 2022 at 11:11 AM, ***@***.***> wrote:   


Hello APKone,

Please try to get your own Youtube Data API Key, this way your website will be independent of my Youtube quotas.

If you don't have Youtube Data API Key, follow this link to register your project and get the API Key
https://console.developers.google.com/



—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by APKone** [comment] 2022-01-05 17:28
any other settings in Google Cloud Platform or Youtube Galllery that need to set other than the API Key

![Goodgle API Key](https://user-images.githubusercontent.com/97009439/148261696-e0278909-829b-4f71-945a-d49148ee5f66.jpg)
![YGAPI](https://user-images.githubusercontent.com/97009439/148261747-69ff3099-e9b9-4d12-865e-373940c812ef.jpg)
?

**Comment by joomlaboat** [comment] 2022-01-05 18:41
Try to use unrestricted key.

**Comment by APKone** [comment] 2022-01-05 19:12
I went into Google Cloud Platform and changed the API restriction to "Don't restrict key", Save.  I will check the site in a few minutes as the comment on the Google states it may take before setting take effect.

**Comment by joomlaboat** [comment] 2022-01-05 20:04
You will need to update the video lists also, open and save it.

**Comment by APKone** [comment] 2022-01-05 20:14
clicked check box on each video list, then update button. opened each video list, Save and Closed button. counts 0

**Comment by joomlaboat** [comment] 2022-01-05 20:40
May I see the video link you have?

**Comment by APKone** [comment] 2022-01-05 20:47
I have three pages setup for youtube videos
http://www.route66moparclub.com/index.php/internet/social-media

![Social Media Page](https://user-images.githubusercontent.com/97009439/148286972-c2991777-88f1-4c23-98d4-7a11549304ee.jpg)

http://www.route66moparclub.com/index.php/internet/route-66

![Route 66 page](https://user-images.githubusercontent.com/97009439/148287050-d52a6475-a572-46df-b4fe-d66a52cc49e8.jpg)

http://www.route66moparclub.com/index.php/internet/restoration

![Restoration Page](https://user-images.githubusercontent.com/97009439/148287075-7c232f09-d8a6-4ae3-b9da-54289e925cf5.jpg)

**Comment by APKone** [comment] 2022-01-14 04:09
Any feedback on what you have seen?

**Comment by APKone** [comment] 2022-02-10 01:39
I still have this issue. Can I get some help?

**Comment by APKone** [comment] 2022-03-21 03:07
Url with "watch?" is working but that only gives me one video instead of a playlist.

Working
https://www.youtube.com/watch?v=SkJh_qO_5UM

Not working
https://www.youtube.com/playlist?list=PLQ5kXCv_WN_iezFBMNuWAzO0F6NGPrWzs

**Comment by joomlaboat** [comment] 2022-03-23 18:58
Its about Youtube Data API key, try to get a new key, or try unrestricted key. Also try without the key that way it will communicate with Joomlaboat.com server instead. I tested it.

![imagen](https://user-images.githubusercontent.com/8064340/159775532-a9fec1c3-c3ef-4b6a-a3e9-80d3ff67f297.png)

**Comment by APKone** [comment] 2022-03-24 01:16
#1 I generated a new key and selected the "Don't restrict key" radio button and saved. Put the new key in the Youtube Gallery Settings key. refreshed and updated all Video lists. No change.

#2  Removed key from Youtube Gallery Settings  key, refreshed and updated all Video lists. On the website is just showing the Views: 0 counter. No video list or screen.

![YoutubeGallery](https://user-images.githubusercontent.com/97009439/159822513-927356ab-39b2-486e-ad96-c8b52745bee9.jpg)

**Comment by joomlaboat** [comment] 2022-03-24 02:20
Same url: 
https://www.youtube.com/playlist?list=PLQ5kXCv_WN_iezFBMNuWAzO0F6NGPrWzs
?
Can you contact me via WhatsApp +507 6084-8737?

**Comment by APKone** [comment] 2022-03-24 02:59
These did not generate any indication of youtube gallery being on the web page, no View 0 counter...
https://www.youtube.com/playlist?list=PLQ5kXCv_WN_iezFBMNuWAzO0F6NGPrWzs  
https://www.youtube.com/c/StellantisNA/videos
https://www.youtube.com/channel/UCsxsyssioAZGzMHGeFxM7lw

What I tried was which is what got me the View 0 counter was...
https://www.youtube.com/results?search_query=stellantis+spotlight
or
https://www.youtube.com/c/StellantisNA/playlists

other pages with View 0 Counter
http://www.route66moparclub.com/index.php/internet/route-66
has
https://www.youtube.com/user/HookedOnRoute66/playlists

http://www.route66moparclub.com/index.php/internet/restoration
has
https://www.youtube.com/c/graveyardcarzshow/playlists

**Comment by joomlaboat** [comment] 2022-03-24 03:12
Its about Quota limitations.

I am going to add a better error management - to not request youtube api if a link is broken. This consumes most of the quota.

**Comment by APKone** [comment] 2022-03-26 01:04
So you will be creating an updated version to install?

**Comment by APKone** [comment] 2022-03-30 01:38
JoomlaBoat.com is down.

![JfactoryNotFound](https://user-images.githubusercontent.com/97009439/160733481-d5fa9e42-d8b7-4185-8685-0e64eeeff543.jpg)

**Comment by APKone** [comment] 2023-01-20 01:45
I see there is an new version I downloaded and updated the website. Then removed the API Key as you have had me to before. But still no video on my page.  http://www.route66moparclub.com/index.php/internet/social-media

**Comment by joomlaboat** [comment] 2023-01-25 17:23
Hi, please try to use your own Youtube Data API key.

Also can you contact me via WhatsApp and I will check on the back-end if it is possible.

**Comment by APKone** [comment] 2023-01-26 02:21
Thanks for the reply. I have added the APIhttp://www.route66moparclub.com/index.php/internet/social-media

I do not use Whatsapp


    On Wednesday, January 25, 2023 at 11:23:37 AM CST, JoomlaBoat ***@***.***> wrote:  
 
 


Hi, please try to use your own Youtube Data API key.

Also can you contact me via WhatsApp and I will check on the back-end if it is possible.

**Comment by APKone** [comment] 2023-01-31 20:28
FYIhttps://www.malwarebytes.com/blog/news/2023/01/protect-your-whatsapp-account-against-actors-who-try-to-steal-it-while-you-sleep?utm_source=blueshift&utm_medium=email&utm_campaign=b2c_pro_oth_20230131_janweeklynewsletter_v4_1_167515092500&utm_content=WhatsApp_hijackers&bsft_aaid=18a8abbd-b7b6-422b-8352-283554e9475a&bsft_eid=c15a8a3b-c7c1-26e7-f217-f3e958e43eda&bsft_clkid=a8683f1b-2956-4bc0-8aea-6dd990fcd75a&bsft_uid=442ba8e4-3555-41e2-b91d-ba05cfc1df2f&bsft_mid=5d80d3d3-46fc-4491-a64a-a0deca64a813&bsft_mime_type=html&bsft_ek=2023-01-31T17%3A05%3A21Z&bsft_lx=11&bsft_tv=24

Sent from Galaxy S8 far, far, away... 
 
  On Wed, Jan 25, 2023 at 8:21 PM, ***@***.***> wrote:    Thanks for the reply. I have added the APIhttp://www.route66moparclub.com/index.php/internet/social-media

I do not use Whatsapp


    On Wednesday, January 25, 2023 at 11:23:37 AM CST, JoomlaBoat ***@***.***> wrote:  
 
 


Hi, please try to use your own Youtube Data API key.

Also can you contact me via WhatsApp and I will check on the back-end if it is possible.

**Comment by APKone** [comment] 2023-05-04 00:57
I am back revisiting this issue again. Uploaded the new version  5.4.9
Played with the links. What I have determined is that https://www.youtube.com/watch?v=5ReK-hsuQkE   works.
Playlists do not work.    https://www.youtube.com/playlist?list=PLQ5kXCv_WN_iezFBMNuWAzO0F6NGPrWzs

**Comment by joomlaboat** [comment] 2023-05-04 12:18
If the playlist is not loaded at all then it's about your Youtube Data API quota. Try to make a new unrestricted key.
I just tried the playlist link and it did load 105 videos.
Does it load some of the videos?

**Comment by APKone** [comment] 2023-05-05 01:31
I generated a new Don't restrict [API] Key, Updated Youtube Gallery Settings with the new API Key.  Performed Update and Refresh of all Video Lists Names. Videos Found still sits at zero for this page.    http://www.route66moparclub.com/index.php/internet/social-media
using https://www.youtube.com/playlist?list=PLQ5kXCv_WN_iezFBMNuWAzO0F6NGPrWzs

This webpage works... http://www.route66moparclub.com/index.php/internet/restoration
It just has 7 individual watch links set like this https://www.youtube.com/watch?v=jA9LWO5KehY

**Comment by joomlaboat** [comment] 2023-05-06 03:12
Hello APKone,

It seams like the problem is with the API Key, I reissued new Keys for JoomlaBoat, inserted the PlayList you provided to one test website, the one that doesn't use it's own Youtube Data API Key, but has the Youtube Gallery activation key. And the result is 105 videos.

Can you contact me via email: support@joomlaboat.com ?

**Comment by APKone** [comment] 2023-06-02 02:18
I responded to your last email after finding it in the spam folder.

**Comment by APKone** [comment] 2023-09-21 00:17
Updated  to verson 5.5.3 in hopes it would fix my issue. Getting attached error message[](url)
![YoutubeGallery5 5 3](https://github.com/joomlaboat/YoutubeGallery/assets/97009439/543ae794-752b-4f49-b0c3-48eafa6be6c8)

**Comment by joomlaboat** [comment] 2023-09-21 00:22
Please check Youtube Gallery settings.
You will need your own Youtube Data API Key.

**Comment by APKone** [comment] 2023-09-21 00:55
I generated a new key and have added in the Youtube Data API Key field


    On Wednesday, September 20, 2023 at 07:22:17 PM CDT, JoomlaBoat ***@***.***> wrote:  
 
 


Please check Youtube Gallery settings.
You will need your own Youtube Data API Key.

**Comment by APKone** [comment] 2023-09-21 01:01
Adding API did not change anything except message prompt is gone.

**Comment by joomlaboat** [comment] 2023-09-21 01:24
Please open and save your video lists.
May I see your website? Can you contact me via email: support@joomlaboat.com?

**Closed as completed** 2024-02-28 17:43 UTC
